server:
  port: 8769

spring:
  application:
    name: service-zuul

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  routes:
    api-business:
      path: /business/**
      service-id: service-business
    api-tracking:
      path: /tracking/**
      service-id: service-tracking
